[Fix]: Table tooltip issue
nuagenetworks/vis-graphs pull request #417
Opened 2020-11-23 12:34 UTC by nxanil

@killanch

Fixed issue #408. Please have a look.

2020-11-30 22:25 UTC, killanch requested changes
@nxanil It is very difficult to navigate to the copy button, the tooltip disappears on mouse move, this needs to be addressed as well. Pls see sample below.

Behavior with code in this PR:
![newtable](https://user-images.githubusercontent.com/24920919/100673052-a9be0880-3317-11eb-9d60-20af39e7c7e3.gif)

Old table behavior:
![oldtable](https://user-images.githubusercontent.com/24920919/100673091-b7738e00-3317-11eb-9cfa-4785dab6fe85.gif)

2020-11-30 22:25 UTC, killanch commented on Graphs/Table/index.js
> +let currentStartIndex = 0;
lets avoid global, instead use state hook,
`const [currentStartIndex, setCurrentStartIndex] = useState(0);`

2020-11-30 22:25 UTC, killanch commented on Graphs/Table/index.js
> +                                                    return onRowsRendered
this prop is a callback function.
to maintain parity with previous version, this should not return anything, instead should invoke InfiniteLoader's onRowsRendered()
```
onRowsRendered={(props) => {
    setCurrentStartIndex(props.startIndex);
    onRowsRendered(props);
}}
```

2020-12-01 11:20 UTC, nxanil commented
@killanch 

Feedback changes have been done. Please verify once.

2020-12-01 18:38 UTC, killanch reviewed
I also noticed that row gets selected when copy button is clicked, is there a way we can avoid row selection? this can be taken up in a separate PR
![tabletooltip-copy](https://user-images.githubusercontent.com/24920919/100782353-235e0100-33c1-11eb-8df5-135b0ed05477.gif)

2020-12-01 18:38 UTC, killanch commented on Graphs/Table/index.js
> +                <p data-tip='' data-for={`tooltip_${cellData}_${columnIndex}_${rowIndex}`} delayUpdate={1000}>{data}</p>
do we need this when tooltip is not applicable? also, is delayUpdate required within paragraph tag?
can we change this as,
```
return !!column.tooltip ?
    <React.Fragment>
        <p data-tip='' data-for={`tooltip_${cellData}_${columnIndex}_${rowIndex}`}>{data}</p>
        {renderTooltip(cellData, columnIndex, rowIndex)}
    </React.Fragment> : data;
```

2020-12-02 01:01 UTC, chaitanyahalbe commented on Graphs/Table/index.js
> +        const top = rowIndex === currentStartIndex ? (rowHeight * (rowIndex + 1)) - 20 : (rowHeight * rowIndex) - 15;
Can you please put a code comment on why you're deduction `20` and `15`? Those numbers seem arbitrary without any comment.

2020-12-07 13:57 UTC, nxanil commented
@killanch 

Feedback changes have been done. Please verify once.

2020-12-07 21:08 UTC, killanch reviewed
@nxanil looks good, thanks

2020-12-07 21:08 UTC, killanch approved these changes

2020-12-07 21:15 UTC, merged